site_name: 构建统一的世界观
site_description: 从物理到意识，从演化到意义的自然主义框架
site_author: 作者姓名
site_url: https://modenl.github.io/entropyandmeaning/

# Repository
repo_name: modenl/entropyandmeaning
repo_url: https://github.com/modenl/entropyandmeaning

# Copyright
copyright: Copyright &copy; 2025 《构建统一的世界观》

# Theme
theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

  features:
    - navigation.instant      # 即时加载
    - navigation.tracking     # 锚点跟踪
    - navigation.tabs         # 顶部标签
    - navigation.sections     # 章节导航
    - navigation.expand       # 展开所有章节
    - navigation.top          # 回到顶部按钮
    - search.suggest          # 搜索建议
    - search.highlight        # 搜索高亮
    - search.share            # 搜索分享
    - content.code.copy       # 代码复制按钮
    - content.tabs.link       # 内容标签链接

  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang:
        - zh
        - en

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra JavaScript for KaTeX
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0.16.9/dist/katex.min.js
  - https://unpkg.com/katex@0.16.9/dist/contrib/auto-render.min.js

# Extra CSS for KaTeX
extra_css:
  - https://unpkg.com/katex@0.16.9/dist/katex.min.css

# Navigation
nav:
  - 首页: index.md
  - 前言: preface.md
  - 第1章 本体论: chapter1.md
  - 第2章 时间、逻辑、因果: chapter2.md
  - 第3章 数学与物理: chapter3.md
  - 第4章 量子力学: chapter4.md
  - 第5章 复杂性与涌现: chapter5.md
  - 第6章 生命与演化: chapter6.md
  - 第7章 意识: chapter7.md
  - 第8章 人工智能: chapter8.md
  - 第9章 意义: chapter9.md
  - 第10章 结论: chapter10.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/modenl/entropyandmeaning
